Increase the memory size of lambda to 512mb
The last 3 hours of lambda runs were failing
to a non-descript "Error: Runtime exited with
error: signal: killed". This Stack overflow
Post (https://bit.ly/3idYKJ6) said to increase
memory which lines up with the log that says
257mb of 256mb was used in the lambda run.